### ISSUE TITLE
incompatible

### ISSUE THREAD

**Issue by OCGDFS** [IDragonfire/OneClickWonder#5]
after the latest server/lobby/game update (idk) the game crashes if u enable the mod
https://pastebin.com/di8jFQYN

**Comment by OCGDFS** [comment]
`Unhandled exception:

state->m_rootState == m_state

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /mean 1785.58 /deviation 94.176 /country DE /clan AoS /init init_faf.lua /numgames 1338 /log C:\ProgramData\FAForever\logs\game.log /nobugreport /savereplay gpgnet://localhost/6191352/Exotic.SCFAreplay /gpgnet 127.0.0.1:56041

Callstack:
	Unknown symbol (address 0x008d462c)

Last 100 lines of log...

debug: Loading module '\000/lua/ui/game/selection.lua\000'
info: Hooked /lua/ui/game/selection.lua with /schook/lua/ui/game/selection.lua
debug: Loading module '\000/lua/keymap/hotkeylabelsui.lua\000'
warning: ...orever\gamedata\lua.nx2\lua\ui\game\construction.lua(83): Attempt to set attribute 'HandleEvent' on nil
warning: stack traceback:
warning:         [C]: in function `error'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\config.lua(12): in function <...alliance\gamedata\mohodata.scd\lua\system\config.lua:11>
warning:         ...orever\gamedata\lua.nx2\lua\ui\game\construction.lua(83): in main chunk
warning:         [C]: in function `doscript'
warning:         [C]: in function `pcall'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
warning:         ...forever\gamedata\lua.nx2\lua\ui\game\commandmode.lua(10): in main chunk
warning:         [C]: in function `doscript'
warning:         [C]: in function `pcall'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
warning:         ...\faforever\gamedata\lua.nx2\lua\ui\game\gamemain.lua(959): in main chunk
warning:         [C]: in function `doscript'
warning:         [C]: in function `pcall'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
warning:         ...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua(85): in function <...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua:83>
warning: ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/lua/ui/game/construction.lua'
warning: stack traceback:
warning:         [C]: in function `error'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
warning:         ...forever\gamedata\lua.nx2\lua\ui\game\commandmode.lua(10): in main chunk
warning:         [C]: in function `doscript'
warning:         [C]: in function `pcall'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
warning:         ...\faforever\gamedata\lua.nx2\lua\ui\game\gamemain.lua(959): in main chunk
warning:         [C]: in function `doscript'
warning:         [C]: in function `pcall'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
warning:         ...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua(85): in function <...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua:83>
warning: ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/lua/ui/game/commandmode.lua'
warning: stack traceback:
warning:         [C]: in function `error'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
warning:         ...\faforever\gamedata\lua.nx2\lua\ui\game\gamemain.lua(959): in main chunk
warning:         [C]: in function `doscript'
warning:         [C]: in function `pcall'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
warning:         ...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua(85): in function <...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua:83>
warning: Error running '/lua/ui/uimain.lua:StartGameUI': ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/lua/ui/game/gamemain.lua'
         stack traceback:
         	[C]: in function `error'
         	...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
         	...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
         	...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua(85): in function <...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua:83>
debug: Loading module '\000/lua/ui/game/commandmode.lua\000'
info: Hooked /lua/ui/game/commandmode.lua with /mods/one click wonder 03/hook/lua/ui/game/commandmode.lua
debug: Loading module '\000/lua/ui/game/construction.lua\000'
debug: Loading module '\000/lua/ui/game/gamemain.lua\000'
info: Hooked /lua/ui/game/gamemain.lua with /mods/zep_minimapzoom/hook/lua/ui/game/gamemain.lua
info: Hooked /lua/ui/game/gamemain.lua with /mods/one click wonder 03/hook/lua/ui/game/gamemain.lua
info: Hooked /lua/ui/game/gamemain.lua with /mods/reveal_positions/hook/lua/ui/game/gamemain.lua
info: Hooked /lua/ui/game/gamemain.lua with /mods/supremescoreboard/hook/lua/ui/game/gamemain.lua
info: Hooked /lua/ui/game/gamemain.lua with /mods/common/hook/lua/ui/game/gamemain.lua
warning: Hotbuild key Shift-C is already bound to action "Capture - SHIFT version" under "ORDERS" category
warning: Hotbuild key Shift-G is already bound to action "Spread attack - SHIFT version" under "ORDERS" category
warning: Hotbuild key Shift-M is already bound to action "Move - SHIFT version" under "ORDERS" category
warning: Hotbuild key Shift-L is already bound to action "Launch a Tactical Missile - SHIFT version" under "ORDERS" category
warning: Hotbuild key Shift-N is already bound to action "Nuke - SHIFT version" under "ORDERS" category
warning: Hotbuild key Shift-F is already bound to action "Ferry - SHIFT version" under "ORDERS" category
warning: Hotbuild key Shift-S is already bound to action "Move" under "ORDERS" category
warning: Hotbuild key Shift-W is already bound to action "Zoom your View out fast" under "CAMERA" category
warning: Hotbuild key Shift-T is already bound to action "Create a build template based on the current selection" under "SELECTION" category
warning: Hotbuild key Shift-U is already bound to action "Transport - SHIFT version" under "ORDERS" category
debug: Loading module '\000/mods/common/select.lua\000'
warning: ...orever\gamedata\lua.nx2\lua\ui\game\construction.lua(83): Attempt to set attribute 'HandleEvent' on nil
warning: stack traceback:
warning:         [C]: in function `error'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\config.lua(12): in function <...alliance\gamedata\mohodata.scd\lua\system\config.lua:11>
warning:         ...orever\gamedata\lua.nx2\lua\ui\game\construction.lua(83): in main chunk
warning:         [C]: in function `doscript'
warning:         [C]: in function `pcall'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
warning:         ...forever\gamedata\lua.nx2\lua\ui\game\commandmode.lua(10): in main chunk
warning:         [C]: in function `doscript'
warning:         [C]: in function `pcall'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
warning:         ...gramdata\faforever\gamedata\lua.nx2\lua\usersync.lua(409): in function <...gramdata\faforever\gamedata\lua.nx2\lua\usersync.lua:408>
warning:         ...gramdata\faforever\gamedata\lua.nx2\lua\usersync.lua(448): in function `OnSync'
warning:         [string "OnSync()"](1): in main chunk
warning: ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/lua/ui/game/construction.lua'
warning: stack traceback:
warning:         [C]: in function `error'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
warning:         ...forever\gamedata\lua.nx2\lua\ui\game\commandmode.lua(10): in main chunk
warning:         [C]: in function `doscript'
warning:         [C]: in function `pcall'
warning:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
warning:         ...gramdata\faforever\gamedata\lua.nx2\lua\usersync.lua(409): in function <...gramdata\faforever\gamedata\lua.nx2\lua\usersync.lua:408>
warning:         ...gramdata\faforever\gamedata\lua.nx2\lua\usersync.lua(448): in function `OnSync'
warning:         [string "OnSync()"](1): in main chunk
warning: Error running lua command: ...gramdata\faforever\gamedata\lua.nx2\lua\usersync.lua(409): Error importing '/lua/ui/game/commandmode.lua'
         stack traceback:
         	[C]: in function `error'
         	...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
         	...gramdata\faforever\gamedata\lua.nx2\lua\usersync.lua(409): in function <...gramdata\faforever\gamedata\lua.nx2\lua\usersync.lua:408>
         	...gramdata\faforever\gamedata\lua.nx2\lua\usersync.lua(448): in function `OnSync'
         	[string "OnSync()"](1): in main chunk
`

**Comment by IDragonfire** [comment]
@OCGDFS I am sorry, I no longer maintain this Mod ...
But I ask in Slack ;)

**Comment by aeoncleanse** [comment]
https://github.com/FAForever/fa/commit/b3c90a73b6158b34c249fbb9eb0e28a4368d64f5

This commit broke it

**Comment by CookieNoob** [comment]
fixed
